import { TaskParamType, TaskType } from "@/types/task";
import { WorkflowTask } from "@/types/workflow";
import { BrainIcon, MousePointerClickIcon } from "lucide-react";

export const ExtractDataWithAITask = {
  type: TaskType.EXTRACT_DATA_WITH_AI,
  label: "Extract Data with AI",
  icon: (props) => <BrainIcon className="stroke-rose-400" {...props} />,
  isEntryPoint: false,
  credits: 4,
  inputs: [
    {
      name: "Content",
      type: TaskParamType.STRING,
      required: true,
      helperText:
        "This is content from a webpage, such as the HTML generated by the get HTML task.",
    },
    {
      name: "Credentials",
      type: TaskParamType.CREDENTIAL,
      required: true,
    },
    {
      name: "Prompt",
      type: TaskParamType.STRING,
      required: true,
      variant: "textarea",
      helperText:
        "This model with return JSON. Then, use the Read Propery From JSON tool to convert each property into the necessary piece of data. \n i.e: Find the selector for the password field(in extract data with AI). -> \n Extract the password selector from this response using the property to JSON tool, and then connect it to the fill input tool.",
    },
  ] as const,
  outputs: [{ name: "Extracted Data", type: TaskParamType.STRING }] as const,
} satisfies WorkflowTask;
